openapi: 3.0.1
info:
  title: Car Rental API Documentation
  version: v1
paths:
  "/api/v1/cars":
    post:
      summary: Create a new car
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                photo:
                  type: string
                price:
                  type: number
                model:
                  type: string
                user_id:
                  type: number
              required:
                - name
                - description
                - photo
                - price
                - model
                - user_id
      responses:
        '200':
          description: Successful
    get:
      summary: List all cars
      responses:
        '200':
          description: Successful

  "/api/v1/cars/{id}":
    parameters:
      - name: id
        in: path
        description: ID of the car
        required: true
        schema:
          type: integer
    get:
      summary: Get a specific car
      responses:
        '200':
          description: Successful
    delete:
      summary: Delete a car
      responses:
        '200':
          description: Successful

  "/api/v1/reservations":
    parameters:
      - name: user_id
        in: path
        description: ID of the user
        required: true
        schema:
          type: integer
    get:
      summary: Get reservations for a user
      tags:
        - Reservations
      responses:
        '200':
          description: Reservations found
        '404':
          description: User not found

    post:
      summary: Create a new reservation for a user
      tags:
        - Reservations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                pick_up:
                  type: string
                return_date:
                  type: string
                car:
                  type: string
                user_id:
                  type: integer
              required:
                - city
                - pick_up
                - return_date
                - car
                - user_id
      responses:
        '201':
          description: Reservation created
        '400':
          description: Invalid request

servers:
  - url: http://localhost:3000
