default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DBUSERNAME'] %>
  password: <%= ENV['DBPASSWORD'] %>

development:
  <<: *default
  database: Car_Rental_Backend_development

test:
  <<: *default
  database: Car_Rental_Backend_test

production:
  <<: *default
  database: Car_Rental_Backend_production
